# Usa a imagem oficial do PHP com Apache
FROM php:7.4-apache

# Atualiza o sistema e instala as dependências necessárias
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Habilita a extensão PostgreSQL para conexão da aplicação com o banco
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pgsql pdo_pgsql

COPY . /var/www/html

# Habilita o módulo de reescrita do Apache (se necessário)
RUN a2enmod rewrite

# Define a porta 80 para acessar a aplicação
EXPOSE 80

# Inicializa o Apache em primeiro plano
CMD ["apache2-foreground"]
